Update realese.yml

diff --git a/.github/workflows/realese.yml b/.github/workflows/realese.yml
--- a/.github/workflows/realese.yml
+++ b/.github/workflows/realese.yml
@@ -24,5 +24,15 @@ jobs:
         
       - name: Run pack
         run: |
-          tag_version=  $(git describe --tags `git rev-list --tags --max-count=1`) || exit $1;
-          echo $tag_version
+          # TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) || { echo "\⛔️ Unable to get a tag.\n"; exit 1;  };
+          TAG_VERSION=2.0.0
+          echo $TAG_VERSION
+          zip -r twitter_counter.$TAG_VERSION.zip build/
+          
+      - name: Upload realese
+        uses: ./.github/workflows/release_uploader
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_REPOSITORY: "anein/twitter-count-characters"
+        
+          
