fix: get tag_version from git

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,8 +2,6 @@ name: Release Action
 
 on:
   push:
-    branches:
-      - master
     tags:
       - v*
 
@@ -22,14 +20,13 @@ jobs:
       - name: Run Building
         run: yarn build
 
-      - name: Run pack
+      - name: Run Pack
         run: |
-          # TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) || { echo "\⛔️ Unable to get a tag.\n"; exit 1;  };
-          TAG_VERSION=2.0.0
+          TAG_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`) || { echo "\⛔️ Unable to get a tag.\n"; exit 1;  };
           echo ::set-env name=TAG_VERSION::${TAG_VERSION}
           zip -r twitter_counter.$TAG_VERSION.zip build/
 
-      - name: Upload realese
+      - name: Upload release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
